/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[pesid]
      ,[data_inversa]
      ,[dia_semana]
      ,[horario]
      ,[uf]
      ,[br]
      ,[km]
      ,[municipio]
      ,[causa_acidente]
      ,[tipo_acidente]
      ,[classificacao_acidente]
      ,[fase_dia]
      ,[sentido_via]
      ,[condicao_metereologica]
      ,[tipo_pista]
      ,[tracado_via]
      ,[uso_solo]
      ,[id_veiculo]
      ,[tipo_veiculo]
      ,[marca]
      ,[ano_fabricacao_veiculo]
      ,[tipo_envolvido]
      ,[estado_fisico]
      ,[idade]
      ,[sexo]
      ,[ilesos]
      ,[feridos_leves]
      ,[feridos_graves]
      ,[mortos]
      ,[latitude]
      ,[longitude]
      ,[regional]
      ,[delegacia]
      ,[uop]
      ,[Arquivo]
      ,[nacionalidade]
      ,[naturalidade]

 select * FROM [Projeto_PucMinas].[PRF].[tblAgrupadoPorPessoa]
  where id = '238868'

  create clustered index idx_principal 
  on [Projeto_PucMinas].[PRF].[tblAgrupadoPorPessoa] (id)

